f=open('optimizer_v2.py','r',encoding='utf-8')
c=f.read()
f.close()
c=c.replace('day_planned * SCALE * 1.5','day_planned * SCALE * 1.1')
c=c.replace('FACTORY_OVERFLOW_WEIGHT = 500','FACTORY_OVERFLOW_WEIGHT = 2000')
c=c.replace('int(round(round(tons_brut, 1) / 10)) * 10','int(round(round(tons_brut, 1) / 5)) * 5')
f=open('optimizer_v2.py','w',encoding='utf-8')
f.write(c)
f.close()
print('OK - 3 corrections appliquees')
