[supabase]
url = "https://mwjefdqfzrtsfzspeppg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13amVmZHFmenJ0c2Z6c3BlcHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzODg3MDgsImV4cCI6MjA5NTk2NDcwOH0.H5IX2uLneHdvwyLJrgN7OrHGrLSZSrQBAuJeuzCEz44"
[users.directeur]
password = "6051fc84a7a0d74c225fb18a496b09952da5642e60723ecae543298edd7d82d6"
role     = "directeur"
name     = "Directeur General"
filter   = ""

[users.fedi]
password = "4c9806477c34233bde7f927e4c32e71f61f18a03d8f1dbbea7eed62b52f68e80"
role     = "commercial"
name     = "FEDI"
filter   = "FEDI"

[users.makki]
password = "dea689708af4c45ef9c7bd4a84a7be0c0cfaf86ea61a25946c91e6372d0b9bd5"
role     = "commercial"
name     = "MAKKI BEN SALAH"
filter   = "MAKKI BEN SALAH"

[users.khalil]
password = "8673b5cfef6d807071848ed5087de701a011ee30cfd8c319a5441ab6c529767b"
role     = "commercial"
name     = "KHALIL"
filter   = "KHALIL"

[users.achref]
password = "9963e33a2017503ba137009a825b2967177532f5ad1454f199cbcae49a6df156"
role     = "commercial"
name     = "ACHREF AJLANI"
filter   = "ACHREF AJLANI"

[users.jilani]
password = "2bcc02eb315a8e31e9c00380096925bd4dd0fbb23c463380bfcdf748040e41b8"
role     = "commercial"
name     = "JILANI OBAY"
filter   = "JILANI OBAY"

[users.comocap]
password = "3f276a837113a5f2d1d39351ec763e37f4b254d9148b5c4cec7f1121183d276f"
role     = "usine"
name     = "COMOCAP"
filter   = "COMOCAP"

[users.sicam]
password = "f6e1df72ff9f1c25236226624b47c6417ee18031eb35f7179aaf12a73bdf24ab"
role     = "usine"
name     = "SICAM"
filter   = "SICAM"

[users.tucal]
password = "9fd85359508dd65535e69b45d7ca357b1b3ae0d36ed3d8438dbf677f5ca83abd"
role     = "usine"
name     = "TUCAL"
filter   = "TUCAL"